apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logto
  template:
    metadata:
      labels:
        app: logto
    spec:
      containers:
        - name: logto
          image: ghcr.io/logto-io/logto
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: logto-env
          ports:
            - containerPort: 3002
            - containerPort: 3001
