apiVersion: v1
kind: Service
metadata:
  name: logto
  namespace: llm
spec:
  selector:
    app: logto
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: NodePort